### ISSUE TITLE
Conversion of dot file to tex causes parsing error.

### ISSUE THREAD

**Issue by Chinmay4400** [kjellmf/dot2tex#78]
I'm trying to convert a dot file to .tex format. I ran into this error :
```
Traceback (most recent call last):
  File "/home/chinmay/anaconda3/envs/tardis/lib/python3.6/site-packages/dot2tex/dot2tex.py", line 332, in parse_drawstring
    didx, cmd = doeE(c, s[idx + 1:])
  File "/home/chinmay/anaconda3/envs/tardis/lib/python3.6/site-packages/dot2tex/dot2tex.py", line 262, in doeE
    points = [float(t) for t in tokens]
  File "/home/chinmay/anaconda3/envs/tardis/lib/python3.6/site-packages/dot2tex/dot2tex.py", line 262, in <listcomp>
    points = [float(t) for t in tokens]
ValueError: could not convert string to float: 'F'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chinmay/anaconda3/envs/tardis/lib/python3.6/site-packages/dot2tex/dot2tex.py", line 3075, in main
    s = conv.convert(dotdata)
  File "/home/chinmay/anaconda3/envs/tardis/lib/python3.6/site-packages/dot2tex/dot2tex.py", line 829, in convert
    self.do_nodes()
  File "/home/chinmay/anaconda3/envs/tardis/lib/python3.6/site-packages/dot2tex/dot2tex.py", line 649, in do_nodes
    s += self.do_drawstring(drawstring, node)
  File "/home/chinmay/anaconda3/envs/tardis/lib/python3.6/site-packages/dot2tex/dot2tex.py", line 536, in do_drawstring
    drawoperations, stat = parse_drawstring(drawstring)
  File "/home/chinmay/anaconda3/envs/tardis/lib/python3.6/site-packages/dot2tex/dot2tex.py", line 347, in parse_drawstring
    log.debug("Failed to parse drawstring %s\n%s", s, err.message)
AttributeError: 'ValueError' object has no attribute 'message'
```
I am using latest versions of pyparsing and graphviz from pypi. I'm attatching the dot file for reference.
[orig.txt](https://github.com/kjellmf/dot2tex/files/4258264/orig.txt)

**Comment by sashank27** [comment]
Hey @Chinmay4400! This issue has been fixed in #83. Please close this issue if this works for you.

**Comment by asg1981rus** [comment]
Hi.
It looks like the issue still persists with the dot file mentioned above. And I do get the same issue with mine file as well.

**Comment by moi90** [comment]
#83 fixed the second exception but not the first.
